/**
 * Images Defines
 * @author Passion UI <passionui.com>
 */

export const Images = {
    logo: require("@assets/images/logo.png"),
    slide: require("@assets/images/slide.png"),
    avata1: require("@assets/images/avata-01.jpeg"),
    avata2: require("@assets/images/avata-02.jpeg"),
    avata3: require("@assets/images/avata-03.jpeg"),
    avata4: require("@assets/images/avata-04.jpeg"),
    car1: require("@assets/images/car-1.jpg"),
    car2: require("@assets/images/car-2.jpg"),
    car3: require("@assets/images/car-3.jpg"),
    car4: require("@assets/images/car-4.jpg"),
    car5: require("@assets/images/car-5.jpg"),
    hotel1: require("@assets/images/hotel-01.jpg"),
    hotel2: require("@assets/images/hotel-02.jpg"),
    hotel3: require("@assets/images/hotel-03.jpg"),
    hotel4: require("@assets/images/hotel-04.jpg"),
    hotel5: require("@assets/images/hotel-05.jpg"),
    hotel6: require("@assets/images/hotel-06.jpg"),
    hotel7: require("@assets/images/hotel-07.jpg"),
    hotel8: require("@assets/images/hotel-08.jpg"),
    interio1: require("@assets/images/interio-1.jpg"),
    interio2: require("@assets/images/interio-2.jpg"),
    interio3: require("@assets/images/interio-3.jpg"),
    interio4: require("@assets/images/interio-4.jpg"),
    interio5: require("@assets/images/interio-5.jpg"),
    interio6: require("@assets/images/interio-6.jpg"),
    profile1: require("@assets/images/profile-1.jpg"),
    profile2: require("@assets/images/profile-2.jpg"),
    profile3: require("@assets/images/profile-3.jpg"),
    profile4: require("@assets/images/profile-4.jpg"),
    profile5: require("@assets/images/profile-5.jpg"),
    profile6: require("@assets/images/profile-6.jpg"),
    profile7: require("@assets/images/profile-7.jpg"),
    profile8: require("@assets/images/profile-8.jpg"),
    trip1: require("@assets/images/trip-1.jpg"),
    trip2: require("@assets/images/trip-2.jpg"),
    trip3: require("@assets/images/trip-3.jpg"),
    trip4: require("@assets/images/trip-4.jpg"),
    trip5: require("@assets/images/trip-5.jpg"),
    trip6: require("@assets/images/trip-6.jpg"),
    trip7: require("@assets/images/trip-7.jpg"),
    trip8: require("@assets/images/trip-8.jpg"),
    trip9: require("@assets/images/trip-9.jpg"),
    room1: require("@assets/images/room-1.jpg"),
    room2: require("@assets/images/room-2.jpg"),
    room3: require("@assets/images/room-3.jpg"),
    room4: require("@assets/images/room-4.jpg"),
    room5: require("@assets/images/room-5.jpg"),
    room6: require("@assets/images/room-6.jpg"),
    room7: require("@assets/images/room-7.jpg"),
    room8: require("@assets/images/room-8.jpg"),
    room9: require("@assets/images/room-9.jpg"),
    room10: require("@assets/images/room-10.jpg"),
    room11: require("@assets/images/room-11.jpg"),
    background1: require("@assets/images/background_01.jpg"),
    background2: require("@assets/images/background_02.jpg"),
    background3: require("@assets/images/background_03.jpg"),
    background4: require("@assets/images/background_04.jpg"),
    banner1: require("@assets/images/banner-1.jpg"),
    banner2: require("@assets/images/banner-2.jpg"),
    airline1: require("@assets/images/airlines-united-states-of-america.png"),
    airline2: require("@assets/images/airlines-singapore.png"),
    airline3: require("@assets/images/airlines-emirates.png"),
    cruise1: require("@assets/images/cruise-1.jpg"),
    cruise2: require("@assets/images/cruise-2.jpg"),
    cruise3: require("@assets/images/cruise-3.jpg"),
    cruise4: require("@assets/images/cruise-4.jpg"),
    brand1: require("@assets/images/cruise-branch-1.png"),
    brand2: require("@assets/images/cruise-branch-2.png"),
    brand3: require("@assets/images/cruise-branch-3.png"),
    brand4: require("@assets/images/cruise-branch-4.png")
};
